import{a as v,S as q,i}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",P="54632285-9bf1eb309cadbee9430723f7a";async function u(s,r=1){return(await v.get(B,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:n,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${t}</p>
          <p><b>Views</b> ${n}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),$.refresh()}function M(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const O=document.querySelector(".form"),E=document.querySelector(".load-more");let c=1,L="",d=0;O.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements.searchQuery.value.trim();if(r){c=1,L=r,M(),l(),p();try{const o=await u(r,c);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}d=o.totalHits,h(o.hits),d>15?b():i.info({message:"We're sorry, but you've reached the end of search results."})}catch{i.error({message:"Something went wrong!"})}finally{g()}}});E.addEventListener("click",async()=>{c+=1,p(),l();try{const s=await u(L,c);h(s.hits),c*15>=d?(l(),i.info({message:"We're sorry, but you've reached the end of search results."})):b();const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong!"})}finally{g()}});
//# sourceMappingURL=index.js.map
